FROM golang:1.23.2

WORKDIR /usr/src/app

ARG JWT_SECRET_KEY
ARG AWS_ACCESS_KEY
ARG AWS_SECRET_KEY

ENV JWT_SECRET_KEY=${JWT_SECRET_KEY}
ENV AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
ENV AWS_SECRET_KEY=${AWS_SECRET_KEY}
ENV MONGODB_URI=${MONGODB_URI}

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

EXPOSE 7000
CMD ["./main"]